### ISSUE TITLE
getting error for me how to fix ?

### ISSUE THREAD

**Issue by somenormalguy7** [DeBos99/adfly-bot#5]
Microsoft Windows [Version 10.0.17763.678]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\shamv>cd desktop/adfly-bot-master

C:\Users\shamv\Desktop\adfly-bot-master>python main.py -d -u www.google.com
[INFO] 570 proxies successfully loaded!
[INFO][1] Connecting to 114.104.131.72:808
[INFO][2] Connecting to 78.128.77.171:8080
[INFO][4] Connecting to 182.19.41.145:80
[INFO][6] Connecting to 60.9.1.250:80
[INFO][8] Connecting to 118.175.240.205:48912
[INFO][10] Connecting to 43.229.95.239:55443
[INFO][12] Connecting to 182.34.32.95:9999
[INFO][14] Connecting to 150.107.205.230:8080
[INFO][1] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0
[INFO][2] Setting user agent to Mozilla/5.0 (X11; Linux i686 on x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
[INFO][4] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
[INFO][6] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:46.0) Gecko/20100101 Firefox/46.0
[INFO][8] Setting user agent to Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2729.30 Safari/537.36
[INFO][10] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2916.28 Safari/537.36
[INFO][12] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:47.0) Gecko/20100101 Firefox/47.0
[INFO][14] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2814.57 Safari/537.36
[INFO][5] Connecting to 13.235.26.161:80
[INFO][9] Connecting to 109.169.14.162:80
[WARNING][1] WebDriverException
[INFO][15] Connecting to 80.50.141.118:53001
[WARNING][2] WebDriverException
[INFO][7] Connecting to 62.99.68.79:44938
[WARNING][6] WebDriverException
[WARNING][12] WebDriverException
Traceback (most recent call last):
[INFO][5] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2784.55 Safari/537.36
Traceback (most recent call last):
[INFO][9] Setting user agent to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2667.41 Safari/537.36
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
[INFO][3] Connecting to 177.105.192.126:43648
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
[WARNING][4] WebDriverException
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
[INFO][7] Setting user agent to Mozilla/5.0 (Windows NT 5.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2928.36 Safari/537.36
Traceback (most recent call last):
FileNotFoundError: [WinError 2] The system cannot find the file specified
[WARNING][14] WebDriverException
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
[INFO][13] Connecting to 89.249.242.67:53281
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

[INFO][15] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Traceback (most recent call last):
[INFO][3] Setting user agent to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2952.83 Safari/537.36
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
[WARNING][10] WebDriverException
Traceback (most recent call last):
[WARNING][7] WebDriverException
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
[INFO][13] Setting user agent to Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/5.0)
FileNotFoundError: [WinError 2] The system cannot find the file specified
[WARNING][8] WebDriverException

During handling of the above exception, another exception occurred:

[INFO][11] Connecting to 104.215.1.174:8080
  File "main.py", line 108, in bot
    driver=webdriver.Chrome(options=chrome_options,executable_path=executable_path)
[WARNING][3] WebDriverException
Traceback (most recent call last):
[WARNING][15] WebDriverException
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
[WARNING][5] WebDriverException
Traceback (most recent call last):
Traceback (most recent call last):
[WARNING][9] WebDriverException
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
[INFO][11] Setting user agent to Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:46.0) Gecko/20100101 Firefox/46.0
Traceback (most recent call last):
[WARNING][13] WebDriverException
Traceback (most recent call last):
[WARNING][11] WebDriverException
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
Traceback (most recent call last):
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
Traceback (most recent call last):
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
Traceback (most recent call last):
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
Traceback (most recent call last):
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
Traceback (most recent call last):
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
Traceback (most recent call last):
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
FileNotFoundError: [WinError 2] The system cannot find the file specified
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

During handling of the above exception, another exception occurred:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "main.py", line 108, in bot
    driver=webdriver.Chrome(options=chrome_options,executable_path=executable_path)
Traceback (most recent call last):
  File "main.py", line 108, in bot
    driver=webdriver.Chrome(options=chrome_options,executable_path=executable_path)
Traceback (most recent call last):
  File "main.py", line 108, in bot
    driver=webdriver.Chrome(options=chrome_options,executable_path=executable_path)
Traceback (most recent call last):
  File "main.py", line 108, in bot
    driver=webdriver.Chrome(options=chrome_options,executable_path=executable_path)
Traceback (most recent call last):
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
  File "main.py", line 108, in bot
    driver=webdriver.Chrome(options=chrome_options,executable_path=executable_path)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[INFO] Exitting with exit code 1
  File "C:\Users\shamv\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\shamv\appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()

C:\Users\shamv\Desktop\adfly-bot-master>

**Comment by DeBos99** [comment]
Did you select correct driver during installation?

**Comment by somenormalguy7** [comment]
yes

**Comment by DeBos99** [comment]
Check if you have `chromedriver.exe` file in `%appdata%\DeBos\drivers`.

**Comment by somenormalguy7** [comment]
> Check if you have `chromedriver.exe` file in `%appdata%\DeBos\drivers`.
There is no just folder called DeBos in %appdata% itself.

**Comment by DeBos99** [comment]
So something went wrong during part of installation.
- Run `python -m pip uninstall selenium`.
- Run bot again and installation should start.
- Select chrome if asked.
- Paste full logs here.

**Comment by somenormalguy7** [comment]
> So something went wrong during part of installation.
> 
> * Run `python -m pip uninstall selenium`.
> * Run bot again and installation should start.
> * Select chrome if asked.
> * Paste full logs here.

It WORKED thank you.
